version: '3.8'
services:
  web:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:80"
      env_file:
        - .env
      volumes:
        - .:/var/www/html #to persist and kep track of changes to the code
      depends_on:
        - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 20s
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./main.sql:/docker-entrypoint-initdb.d/main.sql #run the main.sql script upon startup

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
        - '80:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

  mysqld_exporter:
      image: prom/mysqld-exporter
      environment:
        DATA_SOURCE_NAME: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}"
      command: 
        - "--collect.global_status"
        - "--collect.info_schema.innodb_metrics"
        - "--collect.auto_increment.columns"
        - "--collect.info_schema.processlist"
        - "--collect.binlog_size"
        - "--collect.info_schema.tablestats"
        - "--collect.global_variables"
        - "--collect.info_schema.query_response_time"
        - "--collect.info_schema.userstats"
        - "--collect.info_schema.tables"
        - "--collect.perf_schema.tablelocks"
        - "--collect.perf_schema.file_events"
        - "--collect.perf_schema.eventswaits"
        - "--collect.perf_schema.indexiowaits"
        - "--collect.perf_schema.tableiowaits"
      ports:
        - 9104:9104
      volumes:
        - ./.my.cnf:/.my.cnf

  prometheus:
    image: prom/prometheus
    depends_on:
    - mysqld_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

volumes:
  db_data: