version: '3.8'
services:
  web:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:80"
      env_file:
        - .env
      volumes:
        - .:/var/www/html #to persist and kep track of changes to the code
      depends_on:
        - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 20s
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./main.sql:/docker-entrypoint-initdb.d/main.sql #run the main.sql script upon startup

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
        - '80:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

volumes:
  db_data:

networks:
  app-network: