
apiVersion: v1
kind: Service
metadata:
  name: form-service
spec:
  # type: LoadBalancer
  type: ClusterIP
  # type: NodePort
  selector:
    app: form
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # port: 80
      # targetPort: 80