apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-my-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-my-admin  
  template:
    metadata:
      labels:
        app: php-my-admin  
    spec:
      containers:
        - name: php-my-admin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER