apiVersion: v1
kind: Service
metadata:
  name: php-my-admin-service
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: php-my-admin  
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3000
      # port: 80
      # targetPort: 80