apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: form-ingress
  labels:
    name: form-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: form-service
                port:
                  number: 80
