apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  main.sql: |
    CREATE DATABASE IF NOT EXISTS test_db;
    USE test_db;
    CREATE TABLE users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      message TEXT NOT NULL
    );
